const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');


function generateInvoicePDF(invoice) {
    const doc = new PDFDocument();
  // Your business info (customize as needed)
  const businessName = 'We Bit Play';
  const businessEmail = 'alexei@webitplay.com'; // or hello@webitplay.com
  const businessPhone = '415-656-5950';         // customize
  const website = 'www.webitplay.com';
  

  const filename = `Invoice-${String(invoice.invoiceNumber).padStart(5, '0')}.pdf`;
  const outputPath = path.join(__dirname, '..', 'exports', filename);

  doc.pipe(fs.createWriteStream(outputPath));

  // Header
  // --- Stylized "text logo" & header ---
doc
.fontSize(26)
.fillColor('#333')
.text(businessName.toUpperCase(), 50, 50, { align: 'left' }); // TEXT LOGO

doc
.fontSize(10)
.fillColor('black')
.text(`Email: ${businessEmail}`, 50, 80)
.text(`Phone: ${businessPhone}`, 50, 95)
.text(`Web: ${website}`, 50, 110);

doc
.fontSize(20)
.fillColor('black')
.text(`Invoice #${invoice.invoiceNumber}`, { align: 'right' })
.fontSize(12)
.text(`Date: ${new Date(invoice.date).toDateString()}`, { align: 'right' });

doc.moveDown();


  // Client Info
  doc.moveDown();
  doc.fontSize(16).text('Client Information');
  doc.fontSize(12).text(`${invoice.client.name}`);
  doc.text(`${invoice.client.business}`);
  doc.text(`${invoice.client.address}`);
  doc.text(`Phone: ${invoice.client.phone}`);
  doc.text(`Email: ${invoice.client.email}`);

  // Work Logs
  doc.moveDown();
  doc.fontSize(16).text('Work Log');
  invoice.workLogs.forEach(w => {
    doc.fontSize(12).text(`${w.description} - ${w.hours}h`);
  });

  // Expenses
  if (invoice.expenses.length > 0) {
    doc.moveDown();
    doc.fontSize(16).text('Expenses');
    invoice.expenses.forEach(e => {
      doc.fontSize(12).text(`${e.description} - $${e.amount.toFixed(2)}`);
    });
  }

  // Notes
  if (invoice.notes) {
    doc.moveDown();
    doc.fontSize(16).text('Notes');
    doc.fontSize(12).text(invoice.notes);
  }

  // Total
  doc.moveDown();
  doc.fontSize(16).text(`Total: $${invoice.total.toFixed(2)}`, { align: 'right' });

  // Footer (add here!)
doc.fontSize(10).fillColor('gray')
.text(
  `Generated by ${businessName} | ${new Date().toLocaleString()}`,
  50,
  doc.page.height - 50,
  { align: 'center', lineBreak: false }
);

  doc.end();
  console.log(`📄 PDF generated: ${filename}`);
  
  // Auto-open the PDF after generation (Mac/Linux/Windows)
exec(`open "${outputPath}"`, (err) => {
    if (err) {
      console.error('❌ Failed to open PDF:', err);
    } else {
      console.log(`📂 Opened: ${filename}`);
    }
  });
  
}
module.exports = { generateInvoicePDF };
